#!/bin/sh

api='https://api.mangadex.org'

# perform a get request to an API endpoint
get() {
  endpoint=$1; shift

  [ $# -eq 0 ] &&
    curl -sG "$api$endpoint" |
    sed 's/\\r//g' && return

  printf ' --data-urlencode "%s"' "$@" |
  xargs curl -sG "$api$endpoint" |
  sed 's/\\r//g'
}

# print a variable ignoring special sequences
p() {
  printf '%s' "$*"
}

get_server() {
  get "/at-home/server/$1" | jq -r '.baseUrl'
}

title=$(
  dialog \
    --title "mangadex" \
    --inputbox "search" 0 0 \
    3>&1 1>&2 2>&3 3>&-
)

res=$(get '/manga' "title=$title" | jq -r '.results | to_entries ')
key=$(
  p $res | jq -r '.[] | "\(.key) \"\(.value.data.attributes.title.en)\""' |
    xargs dialog --menu 'results' 0 0 0 \
    3>&1 1>&2 2>&3 3>&-
)

manga=$(p $res | jq -r '.[] | select(.key==0) | .value')
id=$(p $manga | jq -r '.data.id')

lang=$(
  dialog \
    --inputbox "enter your preferred language" 0 0 \
    3>&1 1>&2 2>&3 3>&-
)

chapter_list=$(get '/chapter' "manga=$id" "translatedLanguage=$lang" | jq '.results | to_entries')

key=$(
  p "$chapter_list" |
    jq -r '.[] | "\(.key) \"\(.value.data.attributes.chapter) - \(.value.data.attributes.title)\""' |
    xargs dialog \
      --menu 'select a chapter' 0 0 0 \
      3>&1 1>&2 2>&3 3>&-
)

chapter=$(p "$chapter_list" | jq -r ".[] | select(.key==$key) | .value")
chapter_hash=$(p $chapter | jq -r '.data.attributes.hash')
chapter_id=$(p $chapter | jq -r '.data.id')
server=$(get_server $chapter_id)

cd chapter
page=0

p $chapter | jq -r ".data.attributes.data[] | \"$server/data/$chapter_hash/\(.)\"" |
while read url; do
  dialog \
    --infobox "downloading page $page..." 0 0

  ext=${url##*.}
  curl -s $url -o "$page.$ext"
  
  page=$((page+1))
done
