#!/bin/sh

api='https://api.mangadex.org'

get() {
  endpoint=$1; shift

  [ $# -eq 0 ] &&
    curl -sG "$api$endpoint" |
    tr -d '\r' && return

  printf ' --data-urlencode "%s"' "$@" |
  xargs curl -sG "$api$endpoint" |
  tr -d '\r'
}

search() {
  get '/manga' "title=$1" |
  jq -r '.results[0].data.id'
}

get_chapter() {
  get '/chapter' "manga=$1" |
  jq -r ".results[] | select(.data.attributes.chapter==\"$2\")"
}

get_server() {
  get "/at-home/server/$1" | jq -r '.baseUrl'
}

id=$(search "tomodachi game")
chapter=$(get_chapter $id 1)
chapter_id=$(echo $chapter | jq -r '.data.id')
chapter_hash=$(echo $chapter | jq -r '.data.attributes.hash')
server=$(get_server $chapter_id)

page=0

echo $chapter | jq -r ".data.attributes.data[] | \"$server/data/$chapter_hash/\(.)\"" |
while read url; do
  echo "downloading page $page..."

  ext=${url##*.}
  curl -s $url -o "$page.$ext"
  
  page=$((page+1))
done
