#!/bin/sh

api='https://api.mangadex.org'

get() {
  endpoint=$1; shift
  
  printf ' --data-urlencode "%s"' "$@" |
  xargs curl -sG "$api$endpoint" |
  tr -d '\r'
}

search() {
  get '/manga' "title=$1" |
  jq -r '.results[0].data.id'
}

search "tomodachi game"
